services:
  backend:
    build:
      context: ./docker/backend
    depends_on:
      - db
    working_dir: /backend
    ports:
      - 42069:42069
    volumes:
      - ./backend:/backend
      - /var/run/docker.sock:/var/run/docker.sock
    

  db:
    build:
      context: ./docker/postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: admin_minecraft

volumes:
  database:
